name: "Modrinth Releaser"
description: "Release a version to Modrinth"

branding:
  icon: "upload"
  color: "red"

inputs:
  project_id:
    description: "The Modrinth project ID"
    required: true
  version_number:
    description: "The version number. Ideally will follow semantic versioning"
    required: true
  game_versions:
    description: "The game versions this mod is compatible with"
    required: true
  files:
    description: "The files to upload"
    required: true
  name:
    description: "The name of this version. Defaults to version number."
    required: true
  loaders:
    description: "The loaders this version is compatible with."
    required: true
  changelog:
    description: 'The changelog for this version. Defaults to "Initial release."'
    required: false
    default: ""
  dependencies:
    description: "The dependencies for this version. Defaults to none."
    required: false
    default: ""
  version_type:
    description: "The type of version. Defaults to release."
    required: false
    default: "release"
  featured:
    description: "Whether this version should be featured. Defaults to false."
    required: false
    default: "false"
  status:
    description: "The status of this version."
    required: false
  requested_status:
    description: "The requested status of this version."
    required: false
  upload_mode:
    description: "How will be the version uploaded. Defaults to replace."
    required: false
    default: "replace"

runs:
  using: "node20"
  main: "dist/index.js"
